### ISSUE TITLE
Read the project spec and research parts

### ISSUE THREAD

**Issue by ToddHuaJi** [ToddHuaJi/SDP2019Team6#6]
Read through the project specs and do some research on the parts provided.

Write down questions about the specs so that we can ask/negotiate with the company.

**Comment by ConleyGao** [comment]
since this is shared issue , please comment on  this issue when you are done , last person comment is responsible to close the issue

**Comment by ToddHuaJi** [comment]
I am done

**Comment by ToddHuaJi** [comment]
Closing this because I assume everyone has done this already for the benchside assignment
